name: Deploy `dandidav` to Heroku

on:
  release:
    types: [released]

concurrency:
  # If this workflow is already running, cancel it to avoid a scenario
  # where the older run finishes *after* the newer run and overwrites
  # the deployment with an older version of the app.
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
    CARGO_TERM_COLOR: always

jobs:
  reset-release-branch:
    name: Update release branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch history for all branches and tags
          token: ${{ secrets.GH_TOKEN }} # use PAT with permissions to push to master
          ref: release

      - name: Perform reset
        run: |
          git reset --hard ${{ github.ref }}
          git push --force origin release

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: reset-release-branch
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch history for all branches and tags
          ref: release

      - name: Compile the Rust appication
        run: cargo build --release

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Add Heroku remote and push to it
        run: |
          heroku git:remote -a dandidav
          git push heroku master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY  }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL  }}
